/**
 * Fetch Metadata Perimeter Guard Middleware
 *
 * Implements Phase 3: Zero-Trust Platform Controls.
 *
 * Enforces W3C Fetch Metadata Request Headers (Sec-Fetch-Site, Sec-Fetch-Dest, Sec-Fetch-Mode).
 * Replaces client-side CSRF token handling with unforgeable browser platform invariants:
 * 1. Blocks requests masquerading as subresources (<img>, <script>, <iframe>, <video>, etc.)
 * 2. Blocks unauthorized cross-origin / cross-site requests
 * 3. Provides a cryptographic-grade fallback for legacy clients via Origin / Referer validation
 */

import config from '../config.js';
import { logger } from '../lib/logger.js';

const SAFE_METHODS = new Set(['GET', 'HEAD', 'OPTIONS']);
const STATE_MUTATING_METHODS = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);

/**
 * Normalizes an origin string (stripping trailing slash).
 * @param {string} origin
 * @returns {string}
 */
function normalizeOrigin(origin) {
  if (!origin || typeof origin !== 'string') return '';
  return origin.trim().replace(/\/+$/, '').toLowerCase();
}

/**
 * Evaluates whether an origin matches the configured trusted frontend origin.
 * @param {string} incomingOrigin
 * @param {import('express').Request} req
 * @returns {boolean}
 */
function isTrustedOrigin(incomingOrigin, req) {
  if (!incomingOrigin) return false;
  const normalizedIncoming = normalizeOrigin(incomingOrigin);
  const normalizedConfigured = normalizeOrigin(config.frontendOrigin);

  // 1. Direct match with configured frontend
  if (normalizedIncoming === normalizedConfigured) return true;

  // 2. Same-host match (e.g. in reverse-proxied production environments)
  const host = req.get('host');
  if (host) {
    const protocol = req.protocol || 'http';
    const sameHostOrigin = normalizeOrigin(`${protocol}://${host}`);
    if (normalizedIncoming === sameHostOrigin) return true;
  }

  return false;
}

/**
 * Fetch Metadata Security Perimeter Middleware
 *
 * @param {import('express').Request} req
 * @param {import('express').Response} res
 * @param {import('express').NextFunction} next
 */
export function fetchMetadataGuard(req, res, next) {
  // CORS Preflight OPTIONS requests are handled by CORS middleware
  if (req.method === 'OPTIONS') {
    return next();
  }

  const secFetchSite = req.get('sec-fetch-site');
  const secFetchDest = req.get('sec-fetch-dest');
  const origin = req.get('origin');
  const referer = req.get('referer');

  // =========================================================================
  // 1. MODERN BROWSERS: W3C FETCH METADATA INSPECTION
  // =========================================================================
  if (secFetchSite) {
    // -----------------------------------------------------------------------
    // A. SUBRESOURCE WEAPONIZATION BARRIER (Sec-Fetch-Dest)
    // -----------------------------------------------------------------------
    // All legitimate API queries generated by fetch() or XMLHttpRequest MUST
    // have Sec-Fetch-Dest: 'empty'. Any request with 'image', 'script', 'iframe',
    // 'style', 'audio', etc. is an attacker weaponizing HTML tags cross-site.
    if (secFetchDest && secFetchDest !== 'empty') {
      logger.warn(
        {
          ip: req.ip,
          path: req.originalUrl,
          method: req.method,
          secFetchDest,
          secFetchSite,
          origin,
        },
        '[FetchMetadataGuard] Blocked subresource weaponization attempt'
      );

      return res.status(403).json({
        error: 'Forbidden: API endpoints cannot be targeted as browser subresources',
        code: 'FETCH_METADATA_DISALLOWED_DEST',
      });
    }

    // -----------------------------------------------------------------------
    // B. CROSS-SITE ISOLATION BARRIER (Sec-Fetch-Site)
    // -----------------------------------------------------------------------
    // 1. Same-Origin or Same-Site: Always allowed
    if (secFetchSite === 'same-origin' || secFetchSite === 'same-site') {
      return next();
    }

    // 2. User-initiated navigation (Sec-Fetch-Site: 'none')
    // Allowed only for safe, idempotent read methods
    if (secFetchSite === 'none') {
      if (SAFE_METHODS.has(req.method)) {
        return next();
      }
      return res.status(403).json({
        error: 'Forbidden: State-mutating operations cannot be invoked via direct navigation',
        code: 'FETCH_METADATA_DISALLOWED_MUTATION',
      });
    }

    // 3. Cross-Site (Sec-Fetch-Site: 'cross-site')
    // Allowed strictly if Origin matches our configured trusted frontend
    if (secFetchSite === 'cross-site') {
      if (isTrustedOrigin(origin, req)) {
        return next();
      }

      logger.warn(
        {
          ip: req.ip,
          path: req.originalUrl,
          method: req.method,
          secFetchSite,
          origin,
          trustedOrigin: config.frontendOrigin,
        },
        '[FetchMetadataGuard] Blocked unauthorized cross-site request'
      );

      return res.status(403).json({
        error: 'Forbidden: Cross-site request rejected by isolation policy',
        code: 'FETCH_METADATA_CROSS_SITE_BLOCKED',
      });
    }
  }

  // =========================================================================
  // 2. LEGACY BROWSERS DEFENSIVE FALLBACK (No Sec-Fetch-* support)
  // =========================================================================
  // When Sec-Fetch-Site is absent (older Safari, legacy embedded WebViews),
  // fallback to rigorous verification of Origin and Referer headers.

  // 1. Evaluate explicit Origin header if present
  if (origin) {
    if (isTrustedOrigin(origin, req)) {
      return next();
    }

    logger.warn(
      { ip: req.ip, path: req.originalUrl, method: req.method, origin },
      '[FetchMetadataGuard] Legacy fallback rejected untrusted Origin'
    );
    return res.status(403).json({
      error: 'Forbidden: Untrusted request origin',
      code: 'LEGACY_ORIGIN_MISMATCH',
    });
  }

  // 2. Evaluate Referer header if Origin is absent
  if (referer) {
    try {
      const refererUrl = new URL(referer);
      const refererOrigin = `${refererUrl.protocol}//${refererUrl.host}`;

      if (isTrustedOrigin(refererOrigin, req)) {
        return next();
      }

      logger.warn(
        { ip: req.ip, path: req.originalUrl, method: req.method, refererOrigin },
        '[FetchMetadataGuard] Legacy fallback rejected untrusted Referer origin'
      );
      return res.status(403).json({
        error: 'Forbidden: Untrusted request referer',
        code: 'LEGACY_REFERER_MISMATCH',
      });
    } catch {
      return res.status(403).json({
        error: 'Forbidden: Malformed referer header',
        code: 'LEGACY_MALFORMED_REFERER',
      });
    }
  }

  // 3. Neither Origin nor Referer are present (direct tools or stripped headers)
  // State mutations without verifiable origin provenance are strictly rejected
  if (STATE_MUTATING_METHODS.has(req.method)) {
    logger.warn(
      { ip: req.ip, path: req.originalUrl, method: req.method },
      '[FetchMetadataGuard] Blocked state-mutating request lacking origin proof'
    );
    return res.status(403).json({
      error: 'Forbidden: State mutation requires verifiable origin provenance',
      code: 'LEGACY_MISSING_ORIGIN_PROOF',
    });
  }

  // Safe read requests without origin/referer (e.g. backend health probes or CLI curl) pass through
  return next();
}

export default fetchMetadataGuard;
